#pragma once

typedef struct EnemyEffectConfig {
    uint32_t color;
    float radius;
} EnemyEffectConfig;

static const EnemyEffectConfig enemy_effect_configs[] = {
    {.color = 0, .radius = 0.0f}, // none
    {.color = 0, .radius = 0.0f}, // wall_enemy
    {.color = 0, .radius = 0.0f}, // normal_enemy
    {.color = 0, .radius = 0.0f}, // homing_enemy
    {.color = 0, .radius = 0.0f}, // homing_switch_enemy
    {.color = 0, .radius = 0.0f}, // dasher_enemy
    {.color = 0, .radius = 0.0f}, // dasher_switch_enemy
    {.color = 0xFF000026, .radius = 150.0f}, // slowing_enemy
    {.color = 0x0000FF26, .radius = 150.0f}, // draining_enemy
    {.color = 0x3C007326, .radius = 150.0f}, // gravity_enemy
    {.color = 0xD2E4EF33, .radius = 150.0f}, // repelling_enemy
    {.color = 0, .radius = 0.0f}, // turning_enemy
    {.color = 0, .radius = 0.0f}, // sizing_enemy
    {.color = 0, .radius = 0.0f}, // sniper_enemy
    {.color = 0x3A75704D, .radius = 100.0f}, // freezing_enemy
    {.color = 0, .radius = 0.0f}, // teleporting_enemy
    {.color = 0, .radius = 0.0f}, // wavy_enemy
    {.color = 0, .radius = 0.0f}, // wavy_switch_enemy
    {.color = 0, .radius = 0.0f}, // zigzag_enemy
    {.color = 0, .radius = 0.0f}, // zigzag_switch_enemy
    {.color = 0, .radius = 0.0f}, // confectioner_enemy
    {.color = 0, .radius = 0.0f}, // confectioner_switch_enemy
    {.color = 0, .radius = 0.0f}, // zoning_enemy
    {.color = 0, .radius = 0.0f}, // zoning_switch_enemy
    {.color = 0, .radius = 0.0f}, // spiral_enemy
    {.color = 0, .radius = 0.0f}, // spiral_switch_enemy
    {.color = 0, .radius = 0.0f}, // oscillating_enemy
    {.color = 0, .radius = 0.0f}, // oscillating_switch_enemy
    {.color = 0, .radius = 0.0f}, // switch_enemy
    {.color = 0, .radius = 0.0f}, // dorito_enemy
    {.color = 0, .radius = 0.0f}, // dorito_switch_enemy
    {.color = 0, .radius = 0.0f}, // penny_enemy
    {.color = 0, .radius = 0.0f}, // penny_switch_enemy
    {.color = 0, .radius = 0.0f}, // infinity_enemy
    {.color = 0, .radius = 0.0f}, // infinity_switch_enemy
    {.color = 0, .radius = 0.0f}, // liquid_enemy
    {.color = 0, .radius = 0.0f}, // icicle_enemy
    {.color = 0x21A1A54D, .radius = 165.0f}, // slippery_enemy
    {.color = 0, .radius = 0.0f}, // ice_sniper_enemy
    {.color = 0xFFBFCE80, .radius = 150.0f}, // disabling_enemy
    {.color = 0x3C000033, .radius = 150.0f}, // experience_drain_enemy
    {.color = 0x4D01634D, .radius = 150.0f}, // enlarging_enemy
    {.color = 0, .radius = 0.0f}, // speed_sniper_enemy
    {.color = 0, .radius = 0.0f}, // regen_sniper_enemy
    {.color = 0, .radius = 0.0f}, // radiating_bullets_enemy
    {.color = 0, .radius = 0.0f}, // immune_enemy
    {.color = 0, .radius = 0.0f}, // pumpkin_enemy
    {.color = 0, .radius = 0.0f}, // fake_pumpkin_enemy
    {.color = 0, .radius = 0.0f}, // tree_enemy
    {.color = 0, .radius = 0.0f}, // frost_giant_enemy
    {.color = 0, .radius = 0.0f}, // snowman_enemy
    {.color = 0, .radius = 0.0f}, // corrosive_enemy
    {.color = 0x00C70033, .radius = 150.0f}, // toxic_enemy
    {.color = 0, .radius = 0.0f}, // corrosive_sniper_enemy
    {.color = 0, .radius = 0.0f}, // poison_sniper_enemy
    {.color = 0xBD67D240, .radius = 125.0f}, // magnetic_reduction_enemy
    {.color = 0x6423744D, .radius = 125.0f}, // magnetic_nullification_enemy
    {.color = 0, .radius = 0.0f}, // positive_magnetic_sniper_enemy
    {.color = 0, .radius = 0.0f}, // negative_magnetic_sniper_enemy
    {.color = 0, .radius = 0.0f}, // residue_enemy
    {.color = 0, .radius = 0.0f}, // fire_trail_enemy
    {.color = 0, .radius = 0.0f}, // ice_ghost_enemy
    {.color = 0, .radius = 0.0f}, // poison_ghost_enemy
    {.color = 0, .radius = 0.0f}, // positive_magnetic_ghost_enemy
    {.color = 0, .radius = 0.0f}, // negative_magnetic_ghost_enemy
    {.color = 0, .radius = 0.0f}, // wind_ghost_enemy
    {.color = 0, .radius = 0.0f}, // lunging_enemy
    {.color = 0xF783064D, .radius = 150.0f}, // lava_enemy
    {.color = 0, .radius = 0.0f}, // gravity_ghost_enemy
    {.color = 0, .radius = 0.0f}, // repelling_ghost_enemy
    {.color = 0, .radius = 0.0f}, // star_enemy
    {.color = 0, .radius = 0.0f}, // grass_enemy
    {.color = 0, .radius = 0.0f}, // seedling_enemy
    {.color = 0, .radius = 0.0f}, // flower_enemy
    {.color = 0, .radius = 0.0f}, // disabling_ghost_enemy
    {.color = 0, .radius = 0.0f}, // glowy_enemy
    {.color = 0, .radius = 0.0f}, // firefly_enemy
    {.color = 0, .radius = 0.0f}, // mist_enemy
    {.color = 0, .radius = 0.0f}, // phantom_enemy
    {.color = 0, .radius = 0.0f}, // cybot_enemy
    {.color = 0, .radius = 0.0f}, // eabot_enemy
    {.color = 0, .radius = 0.0f}, // wabot_enemy
    {.color = 0, .radius = 0.0f}, // fibot_enemy
    {.color = 0, .radius = 0.0f}, // aibot_enemy
    {.color = 0, .radius = 0.0f}, // wind_sniper_enemy
    {.color = 0, .radius = 0.0f}, // sand_enemy
    {.color = 0, .radius = 0.0f}, // sandrock_enemy
    {.color = 0x6C541E4D, .radius = 150.0f}, // quicksand_enemy
    {.color = 0, .radius = 0.0f}, // crumbling_enemy
    {.color = 0x99999933, .radius = 150.0f}, // radar_enemy
    {.color = 0x29FFC64D, .radius = 100.0f}, // barrier_enemy
    {.color = 0, .radius = 0.0f}, // speed_ghost_enemy
    {.color = 0, .radius = 0.0f}, // regen_ghost_enemy
    {.color = 0, .radius = 0.0f}, // cactus_enemy
    {.color = 0, .radius = 0.0f}, // cycling_enemy
    {.color = 0, .radius = 0.0f}, // icbot_enemy
    {.color = 0, .radius = 0.0f}, // elbot_enemy
    {.color = 0, .radius = 0.0f}, // plbot_enemy
    {.color = 0, .radius = 0.0f}, // mebot_enemy
    {.color = 0, .radius = 0.0f}, // libot_enemy
    {.color = 0, .radius = 0.0f}, // dabot_enemy
    {.color = 0, .radius = 0.0f}, // sparking_enemy
    {.color = 0, .radius = 0.0f}, // thunderbolt_enemy
    {.color = 0, .radius = 0.0f}, // static_enemy
    {.color = 0, .radius = 0.0f}, // electrical_enemy
    {.color = 0, .radius = 0.0f}, // powered_enemy
    {.color = 0, .radius = 0.0f}, // prediction_sniper_enemy
    {.color = 0, .radius = 0.0f}, // ring_sniper_enemy
    {.color = 0, .radius = 0.0f}, // charging_enemy
    {.color = 0, .radius = 0.0f}, // reducing_enemy
    {.color = 0, .radius = 0.0f}, // lead_sniper_enemy
    {.color = 0, .radius = 0.0f}, // stalactite_enemy
    {.color = 0xBF52134D, .radius = 150.0f}, // blocking_enemy
    {.color = 0, .radius = 0.0f}, // force_sniper_a_enemy
    {.color = 0, .radius = 0.0f}, // force_sniper_b_enemy
    {.color = 0, .radius = 0.0f}, // wacky_wall_enemy
    {.color = 0xAA2F2F7A, .radius = 140.0f}, // flaming_enemy
    {.color = 0, .radius = 0.0f}, // stumbling_enemy
    {.color = 0x4641422B, .radius = 220.0f}, // disarming_enemy
    {.color = 0, .radius = 0.0f}, // lurching_enemy
    {.color = 0, .radius = 0.0f}, // infectious_enemy
    {.color = 0, .radius = 0.0f}, // mutating_enemy
    {.color = 0, .radius = 0.0f}, // vengeful_soul_enemy
    {.color = 0, .radius = 0.0f}, // lost_soul_enemy
    {.color = 0, .radius = 0.0f}, // blind_enemy
    {.color = 0, .radius = 0.0f}, // ninja_star_sniper_enemy
    {.color = 0, .radius = 0.0f}, // summoner_enemy
    {.color = 0, .radius = 0.0f}, // slasher_enemy
    {.color = 0, .radius = 0.0f}, // lotus_flower_enemy
    {.color = 0, .radius = 0.0f}, // void_crawler_enemy
    {.color = 0, .radius = 0.0f}, // void_swarm_enemy
    {.color = 0, .radius = 0.0f}, // void_sniper_enemy
    {.color = 0, .radius = 0.0f}, // dripping_enemy
    {.color = 0x26123526, .radius = 150.0f}, // void_drain_enemy
    {.color = 0x75265626, .radius = 100.0f}, // withering_enemy
    {.color = 0, .radius = 0.0f}, // superstar_enemy
};
